var = input("digite algo: ")
print('O tipo de "{}" é ' .format(var), type(var) )
print('"{}" só tem espaços? '.format(var), var.isspace())
print('"{}" é um número? '.format(var), var.isnumeric())
print('"{}" é alfabetico? '.format(var), var.isalpha())
print('"{}" é alfanumérico? '.format(var), var.isalnum())
print('"{}" está em maiscula? '.format(var), var.isupper())
print('"{}" está em minuscula? '.format(var), var.islower())
print('"{}" está capitalizada? '.format(var), var.istitle())
